title: Kiersten Bustos # your name (or website title) here
logo: "/images/1605623546118.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my site! This portfolio refelcts the projects I have created both in school and professional work.
  <br><br>
  I am currently an HR professional focused on employee retention who will be transitioning from the military in the next twelve months. 
  My education is in Environmental Management with a focus on water resources management. 
  Even though these career fields seem very different, they both use my passions for complex problem solving, data management, 
  and bringing people together to find mutually agreeable solutions.
 
  <br><br>
  <a href="www.linkedin.com/in/kiersten-bustos/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
